global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost:8000
          - app:8000
          - host.docker.internal:8000